name: Build and push Docker image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn build
        run: |
          yarn tsc
          yarn build:backend
        working-directory: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: '.'
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backstage-app:latest
            ghcr.io/${{ github.repository_owner }}/backstage-app:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/backstage-app:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.description=Docker image for ${{ github.repository_owner }} backstage site
