name: Build and push Docker image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: backstage
          ref: v${{ github.event.client_payload.version }}

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: yarn install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable
      # End of yarn setup

      - name: yarn build
        run: yarn build
        working-directory: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: '.'
          file: ./packages/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backstage-app:latest
            ghcr.io/${{ github.repository_owner }}/backstage-app:$GITHUB_SHA
            ghcr.io/${{ github.repository_owner }}/backstage-app:$GITHUB_REF_NAME
          labels: |
            org.opencontainers.image.description=Docker image for ${{ github.repository_owner }} backstage site
